CREATE TABLE IF NOT EXISTS opt_ins (
    quan_address VARCHAR(64) PRIMARY KEY REFERENCES addresses(quan_address) ON DELETE CASCADE,
    opt_in_number INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_opt_ins_number_unique ON opt_ins (opt_in_number);

ALTER TABLE addresses DROP COLUMN IF EXISTS is_reward_program_participant;

